### ISSUE TITLE
what happened

### ISSUE THREAD

**Issue by leoireo** [ScopesDK/PrimeRose-LuaExecutor#1]
what happened between you 2

**Comment by xo1337** [comment]
> what happened between you 2

Nothing happened lol. Btw this isn't even the real primerose src, because if it was where is the actual buttons with the correct icons and the top where it should say your username lmao. This is just a pasted src and he basically took my code for the ui i gave him and now calls it "primerose source code" LOL. Plus the "bypass" he claims is his own hard work, isn't his :), He just got it of someone named Serse. So scopes, my last message to you. Stop being a skid and stealing peoples shit and claiming as your own work :) Grow up and learn how to actually program. Have a nice day :)

**Comment by ScopesDK** [comment]
still sad because ur bypass it out kid??

**Comment by 0x98a** [comment]
> > what happened between you 2
> 
> Nothing happened lol. Btw this isn't even the real primerose src, because if it was where is the actual buttons with the correct icons and the top where it should say your username lmao. This is just a pasted src and he basically took my code for the ui i gave him and now calls it "primerose source code" LOL. Plus the "bypass" he claims is his own hard work, isn't his :), He just got it of someone named Serse. So scopes, my last message to you. Stop being a skid and stealing peoples shit and claiming as your own work :) Grow up and learn how to actually program. Have a nice day :)

Nigga, shut the fuck up. You just mad that you cant update without scopes. What happen to the discord after you kicked scopes?  Everything gone. You sit on your ass each and every day and shit talk people on unknowncheats because you have 500 reputation on a cheating forum? Go out and get a social life and stop being a asocial kiddo thinking you are the best, and then say to other "i am the best bc i am the imgui god". Anyways you wont get far in life with your skidded things and your "ImGui god" nickname.

**Comment by HeaveN-Bytes** [comment]
> > > what happened between you 2
> > 
> > 
> > Nothing happened lol. Btw this isn't even the real primerose src, because if it was where is the actual buttons with the correct icons and the top where it should say your username lmao. This is just a pasted src and he basically took my code for the ui i gave him and now calls it "primerose source code" LOL. Plus the "bypass" he claims is his own hard work, isn't his :), He just got it of someone named Serse. So scopes, my last message to you. Stop being a skid and stealing peoples shit and claiming as your own work :) Grow up and learn how to actually program. Have a nice day :)
> 
> Nigga, shut the fuck up. You just mad that you cant update without scopes. What happen to the discord after you kicked scopes? Everything gone. You sit on your ass each and every day and shit talk people on unknowncheats because you have 500 reputation on a cheating forum? Go out and get a social life and stop being a asocial kiddo thinking you are the best, and then say to other "i am the best bc i am the imgui god". Anyways you wont get far in life with your skidded things and your "ImGui god" nickname.
> 
> -- Looking forward to your reply, canada kiddo.

bro its not even the real source 🤣 xo would never give a skid like this fucking source lmfao you need to get your head out of the gutter

**Comment by 0x98a** [comment]
> > > > what happened between you 2

Then why the fuck did it go down and get detected after scopes got kicked, and it worked while he was there. Get some braincells talking, you dont know a shit about what happen. The man literally calls himself the ImGui god?? Like go read the docs and then you can make the same ui + he wont even respond to me because he knows that i am talking facts.

**Comment by xo1337** [comment]
> > > > > what happened between you 2
> 
> Then why the fuck did it go down and get detected after scopes got kicked, and it worked while he was there. Get some braincells talking, you dont know a shit about what happen. The man literally calls himself the ImGui god?? Like go read the docs and then you can make the same ui + he wont even respond to me because he knows that i am talking facts.
> 
> * You name is literally HeaveN-Bytes and location is HeavenCheats and still your a no namer in fivem. I can prove every point i have in this discussion.

Scopes gave me a bypass that wasn't even his lmao and claims in this src its his "hard work" 😂 Kind of sad to see you defending someone who doesn't understand basic C++ knowledge haha. You can talk all the shit you want, but just remember it doesn't harm or effect me in any way shape or form. You say that i won't succeed in life? You must be a really sad person to go that far saying things like that to other people. Grow up already.

**Comment by 0x98a** [comment]
> > > > > > what happened between you 2
> > 
> > 
> > Then why the fuck did it go down and get detected after scopes got kicked, and it worked while he was there. Get some braincells talking, you dont know a shit about what happen. The man literally calls himself the ImGui god?? Like go read the docs and then you can make the same ui + he wont even respond to me because he knows that i am talking facts.
> > 
> > * You name is literally HeaveN-Bytes and location is HeavenCheats and still your a no namer in fivem. I can prove every point i have in this discussion.
> 
> Scopes gave me a bypass that wasn't even his lmao and claims in this src its his "hard work" 😂 Kind of sad to see you defending someone who doesn't understand basic C++ knowledge haha. You can talk all the shit you want, but just remember it doesn't harm or effect me in any way shape or form. You say that i won't succeed in life? You must be a really sad person to go that far saying things like that to other people. Grow up already.

Your buyers literally says ur an idiot, what happen to primerose after you kicked scopes? went down. Both of you knows basic C++ and shit, just because you can do imgui and edit styles doesnt mean you are the "ImGui god". Funny how shits working after scopes is coming into the project and it goes down when he is out.

https://cdn.discordapp.com/attachments/835643659080564736/849984267051335720/916g1EoA.png
Cant do shit without him, tell everyone the truth canada kiddo.

**Comment by xo1337** [comment]
> > > > > > > what happened between you 2
> > > 
> > > 
> > > Then why the fuck did it go down and get detected after scopes got kicked, and it worked while he was there. Get some braincells talking, you dont know a shit about what happen. The man literally calls himself the ImGui god?? Like go read the docs and then you can make the same ui + he wont even respond to me because he knows that i am talking facts.
> > > 
> > > * You name is literally HeaveN-Bytes and location is HeavenCheats and still your a no namer in fivem. I can prove every point i have in this discussion.
> > 
> > 
> > Scopes gave me a bypass that wasn't even his lmao and claims in this src its his "hard work" 😂 Kind of sad to see you defending someone who doesn't understand basic C++ knowledge haha. You can talk all the shit you want, but just remember it doesn't harm or effect me in any way shape or form. You say that i won't succeed in life? You must be a really sad person to go that far saying things like that to other people. Grow up already.
> 
> Your buyers literally says ur an idiot, what happen to primerose after you kicked scopes? went down. Both of you knows basic C++ and shit, just because you can do imgui and edit styles doesnt mean you are the "ImGui god". Funny how shits working after scopes is coming into the project and it goes down when he is out.
> 
> https://cdn.discordapp.com/attachments/835643659080564736/849984267051335720/916g1EoA.png
> Cant do shit without him, tell everyone the truth canada kiddo.

I can't do shit without him? Thats why i made an entire auth system, secure loader, undetected injector? 😂 Good one haha. Funny you defend scopes when he can't even properly code a cheat. He relys on lots of other people to spoon feed him the answer. He was begging Serse for the method he found for executing in a resource 😂. Scopes can't even use Reclass.net , but yet he calls himself a reverse engineer? 😂 You can't be serious. Stop continuing this as you're just digging your self the biggest hole in your ass. Have a nice day

**Comment by ScopesDK** [comment]
xo out here palying big but cant do shit  // Issue Closed

**Comment by 0x98a** [comment]
> > > > > > > > what happened between you 2
> > > > 
> > > > 
> > > > Then why the fuck did it go down and get detected after scopes got kicked, and it worked while he was there. Get some braincells talking, you dont know a shit about what happen. The man literally calls himself the ImGui god?? Like go read the docs and then you can make the same ui + he wont even respond to me because he knows that i am talking facts.
> > > > 
> > > > * You name is literally HeaveN-Bytes and location is HeavenCheats and still your a no namer in fivem. I can prove every point i have in this discussion.
> > > 
> > > 
> > > Scopes gave me a bypass that wasn't even his lmao and claims in this src its his "hard work" 😂 Kind of sad to see you defending someone who doesn't understand basic C++ knowledge haha. You can talk all the shit you want, but just remember it doesn't harm or effect me in any way shape or form. You say that i won't succeed in life? You must be a really sad person to go that far saying things like that to other people. Grow up already.
> > 
> > 
> > Your buyers literally says ur an idiot, what happen to primerose after you kicked scopes? went down. Both of you knows basic C++ and shit, just because you can do imgui and edit styles doesnt mean you are the "ImGui god". Funny how shits working after scopes is coming into the project and it goes down when he is out.
> > https://cdn.discordapp.com/attachments/835643659080564736/849984267051335720/916g1EoA.png
> > Cant do shit without him, tell everyone the truth canada kiddo.
> 
> I can't do shit without him? Thats why i made an entire auth system, secure loader, undetected injector? 😂 Good one haha. Funny you defend scopes when he can't even properly code a cheat. He relys on lots of other people to spoon feed him the answer. He was begging Serse for the method he found for executing in a resource 😂. Scopes can't even use Reclass.net , but yet he calls himself a reverse engineer? 😂 You can't be serious. Stop continuing this as you're just digging your self the biggest hole in your ass. Have a nice day

Yea, i checked your whole website. Nigga it was skidded? Stfu, u cant do shit without. Stop calling yourself the ImGui God.... Thanks // Issue Closed
